// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class ActiveIngredient
    {
        public ActiveIngredient()
        {
            ContraIndication = new HashSet<ContraIndication>();
            MedInteractionActiveIngredient = new HashSet<MedInteractionActiveIngredient>();
            MedicationInteraction = new HashSet<MedicationInteraction>();
            MedicationRecord = new HashSet<MedicationRecord>();
            PatientAllergy = new HashSet<PatientAllergy>();
        }

        public int IngredientId { get; set; }
        public string IngredientDescription { get; set; }
        public int? StrengthId { get; set; }

        public virtual ActiveIngredientStrength Strength { get; set; }
        public virtual ICollection<ContraIndication> ContraIndication { get; set; }
        public virtual ICollection<MedInteractionActiveIngredient> MedInteractionActiveIngredient { get; set; }
        public virtual ICollection<MedicationInteraction> MedicationInteraction { get; set; }
        public virtual ICollection<MedicationRecord> MedicationRecord { get; set; }
        public virtual ICollection<PatientAllergy> PatientAllergy { get; set; }
    }
}