// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class ActiveIngredientStrength
    {
        public ActiveIngredientStrength()
        {
            ActiveIngredient = new HashSet<ActiveIngredient>();
        }

        public int StrengthId { get; set; }
        public string StrengthDescription { get; set; }

        public virtual ICollection<ActiveIngredient> ActiveIngredient { get; set; }
    }
}