// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class Admin
    {
        public int AdminId { get; set; }

        public virtual User User { get; set; }
    }
}