// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class ConditionDiagnosis
    {
        public ConditionDiagnosis()
        {
            ChronicHistory = new HashSet<ChronicHistory>();
            ContraIndication = new HashSet<ContraIndication>();
            Prescription = new HashSet<Prescription>();
        }

        public int ConditionId { get; set; }
        public string ConditionDecription { get; set; }

        public virtual ICollection<ChronicHistory> ChronicHistory { get; set; }
        public virtual ICollection<ContraIndication> ContraIndication { get; set; }
        public virtual ICollection<Prescription> Prescription { get; set; }
    }
}