// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class Doctor
    {
        public Doctor()
        {
            ChronicHistory = new HashSet<ChronicHistory>();
            ChronicMedication = new HashSet<ChronicMedication>();
            PatientAllergy = new HashSet<PatientAllergy>();
            PatientDoctorVisit = new HashSet<PatientDoctorVisit>();
        }

        public int DoctorId { get; set; }
        public string Hcrn { get; set; }
        public int? QualificationId { get; set; }
        public int? MedicalPracticeId { get; set; }

        public virtual MedicalPractice MedicalPractice { get; set; }
        public virtual HighestQualification Qualification { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ChronicHistory> ChronicHistory { get; set; }
        public virtual ICollection<ChronicMedication> ChronicMedication { get; set; }
        public virtual ICollection<PatientAllergy> PatientAllergy { get; set; }
        public virtual ICollection<PatientDoctorVisit> PatientDoctorVisit { get; set; }
    }
}