// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace E_prescription
{
    public partial class EPrescriptiondbContext : DbContext
    {
        public EPrescriptiondbContext()
        {
        }

        public EPrescriptiondbContext(DbContextOptions<EPrescriptiondbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ActiveIngredient> ActiveIngredient { get; set; }
        public virtual DbSet<ActiveIngredientStrength> ActiveIngredientStrength { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<ChronicHistory> ChronicHistory { get; set; }
        public virtual DbSet<ChronicMedication> ChronicMedication { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<ConditionDiagnosis> ConditionDiagnosis { get; set; }
        public virtual DbSet<ContraIndication> ContraIndication { get; set; }
        public virtual DbSet<DispensedMedication> DispensedMedication { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<DosageForm> DosageForm { get; set; }
        public virtual DbSet<HighestQualification> HighestQualification { get; set; }
        public virtual DbSet<InteractionLevel> InteractionLevel { get; set; }
        public virtual DbSet<MedInteractionActiveIngredient> MedInteractionActiveIngredient { get; set; }
        public virtual DbSet<MedicalPractice> MedicalPractice { get; set; }
        public virtual DbSet<MedicationInteraction> MedicationInteraction { get; set; }
        public virtual DbSet<MedicationRecord> MedicationRecord { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientAllergy> PatientAllergy { get; set; }
        public virtual DbSet<PatientDoctorVisit> PatientDoctorVisit { get; set; }
        public virtual DbSet<Pharmacist> Pharmacist { get; set; }
        public virtual DbSet<Pharmacy> Pharmacy { get; set; }
        public virtual DbSet<Prescription> Prescription { get; set; }
        public virtual DbSet<PrescriptionMedication> PrescriptionMedication { get; set; }
        public virtual DbSet<Repeat> Repeat { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Suburb> Suburb { get; set; }
        public virtual DbSet<User> User { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<ActiveIngredient>(entity =>
            {
                entity.HasKey(e => e.IngredientId);

                entity.Property(e => e.IngredientId)
                    .ValueGeneratedNever()
                    .HasColumnName("IngredientID");

                entity.Property(e => e.IngredientDescription).HasMaxLength(50);

                entity.Property(e => e.StrengthId).HasColumnName("StrengthID");

                entity.HasOne(d => d.Strength)
                    .WithMany(p => p.ActiveIngredient)
                    .HasForeignKey(d => d.StrengthId)
                    .HasConstraintName("FK_ActiveIngredient_ActiveIngredientStrength");
            });

            modelBuilder.Entity<ActiveIngredientStrength>(entity =>
            {
                entity.HasKey(e => e.StrengthId);

                entity.Property(e => e.StrengthId)
                    .ValueGeneratedNever()
                    .HasColumnName("StrengthID");

                entity.Property(e => e.StrengthDescription).HasMaxLength(50);
            });

            modelBuilder.Entity<Admin>(entity =>
            {
                entity.Property(e => e.AdminId)
                    .ValueGeneratedNever()
                    .HasColumnName("AdminID");
            });

            modelBuilder.Entity<ChronicHistory>(entity =>
            {
                entity.HasKey(e => e.ChronicId);

                entity.Property(e => e.ChronicId)
                    .ValueGeneratedNever()
                    .HasColumnName("ChronicID");

                entity.Property(e => e.ConditionId).HasColumnName("ConditionID");

                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.Property(e => e.DoctorId).HasColumnName("DoctorID");

                entity.Property(e => e.PatientId).HasColumnName("PatientID");

                entity.HasOne(d => d.Condition)
                    .WithMany(p => p.ChronicHistory)
                    .HasForeignKey(d => d.ConditionId)
                    .HasConstraintName("FK_ChronicHistory_ConditionDiagnosis");

                entity.HasOne(d => d.Doctor)
                    .WithMany(p => p.ChronicHistory)
                    .HasForeignKey(d => d.DoctorId)
                    .HasConstraintName("FK_ChronicHistory_Doctor");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.ChronicHistory)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK_ChronicHistory_Patient");
            });

            modelBuilder.Entity<ChronicMedication>(entity =>
            {
                entity.Property(e => e.ChronicMedicationId)
                    .ValueGeneratedNever()
                    .HasColumnName("ChronicMedicationID");

                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.Property(e => e.DoctorId).HasColumnName("DoctorID");

                entity.Property(e => e.MedicationId).HasColumnName("MedicationID");

                entity.Property(e => e.PatientId).HasColumnName("PatientID");

                entity.HasOne(d => d.Doctor)
                    .WithMany(p => p.ChronicMedication)
                    .HasForeignKey(d => d.DoctorId)
                    .HasConstraintName("FK_ChronicMedication_Doctor");

                entity.HasOne(d => d.Medication)
                    .WithMany(p => p.ChronicMedication)
                    .HasForeignKey(d => d.MedicationId)
                    .HasConstraintName("FK_ChronicMedication_MedicationRecord");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.ChronicMedication)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK_ChronicMedication_Patient");
            });

            modelBuilder.Entity<City>(entity =>
            {
                entity.Property(e => e.CityId)
                    .ValueGeneratedNever()
                    .HasColumnName("CityID");

                entity.Property(e => e.CityName).HasMaxLength(50);

                entity.Property(e => e.PostalCode)
                    .HasMaxLength(4)
                    .IsFixedLength(true);
            });

            modelBuilder.Entity<ConditionDiagnosis>(entity =>
            {
                entity.HasKey(e => e.ConditionId);

                entity.Property(e => e.ConditionId)
                    .ValueGeneratedNever()
                    .HasColumnName("ConditionID");

                entity.Property(e => e.ConditionDecription).HasMaxLength(50);
            });

            modelBuilder.Entity<ContraIndication>(entity =>
            {
                entity.Property(e => e.ContraIndicationId)
                    .ValueGeneratedNever()
                    .HasColumnName("ContraIndicationID");

                entity.Property(e => e.ConditionId).HasColumnName("ConditionID");

                entity.Property(e => e.ContraIndicationName).HasMaxLength(50);

                entity.Property(e => e.IngredientId).HasColumnName("IngredientID");

                entity.HasOne(d => d.Condition)
                    .WithMany(p => p.ContraIndication)
                    .HasForeignKey(d => d.ConditionId)
                    .HasConstraintName("FK_ContraIndication_ConditionDiagnosis");

                entity.HasOne(d => d.Ingredient)
                    .WithMany(p => p.ContraIndication)
                    .HasForeignKey(d => d.IngredientId)
                    .HasConstraintName("FK_ContraIndication_ActiveIngredient");
            });

            modelBuilder.Entity<DispensedMedication>(entity =>
            {
                entity.Property(e => e.DispensedMedicationId)
                    .ValueGeneratedNever()
                    .HasColumnName("DispensedMedicationID");

                entity.Property(e => e.ContraIndicationId).HasColumnName("ContraIndicationID");

                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.Property(e => e.DosageId).HasColumnName("DosageID");

                entity.Property(e => e.MedInteractionId).HasColumnName("MedInteractionID");

                entity.Property(e => e.MedicationId).HasColumnName("MedicationID");

                entity.Property(e => e.PatientId).HasColumnName("PatientID");

                entity.Property(e => e.PharmacistId).HasColumnName("PharmacistID");

                entity.Property(e => e.Quantity).HasMaxLength(50);

                entity.Property(e => e.WarningIgnoreReason).HasMaxLength(50);

                entity.HasOne(d => d.ContraIndication)
                    .WithMany(p => p.DispensedMedication)
                    .HasForeignKey(d => d.ContraIndicationId)
                    .HasConstraintName("FK_DispensedMedication_ContraIndication");

                entity.HasOne(d => d.Dosage)
                    .WithMany(p => p.DispensedMedication)
                    .HasForeignKey(d => d.DosageId)
                    .HasConstraintName("FK_DispensedMedication_DosageForm");

                entity.HasOne(d => d.MedInteraction)
                    .WithMany(p => p.DispensedMedication)
                    .HasForeignKey(d => d.MedInteractionId)
                    .HasConstraintName("FK_DispensedMedication_MedicationInteraction");

                entity.HasOne(d => d.Medication)
                    .WithMany(p => p.DispensedMedication)
                    .HasForeignKey(d => d.MedicationId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DispensedMedication_MedicationRecord");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.DispensedMedication)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK_DispensedMedication_Patient");

                entity.HasOne(d => d.Pharmacist)
                    .WithMany(p => p.DispensedMedication)
                    .HasForeignKey(d => d.PharmacistId)
                    .HasConstraintName("FK_DispensedMedication_Pharmacist");
            });

            modelBuilder.Entity<Doctor>(entity =>
            {
                entity.Property(e => e.DoctorId)
                    .ValueGeneratedNever()
                    .HasColumnName("DoctorID");

                entity.Property(e => e.Hcrn)
                    .HasMaxLength(50)
                    .HasColumnName("HCRN");

                entity.Property(e => e.MedicalPracticeId).HasColumnName("MedicalPracticeID");

                entity.Property(e => e.QualificationId).HasColumnName("QualificationID");

                entity.HasOne(d => d.MedicalPractice)
                    .WithMany(p => p.Doctor)
                    .HasForeignKey(d => d.MedicalPracticeId)
                    .HasConstraintName("FK_Doctor_MedicalPractice");

                entity.HasOne(d => d.Qualification)
                    .WithMany(p => p.Doctor)
                    .HasForeignKey(d => d.QualificationId)
                    .HasConstraintName("FK_Doctor_HighestQualification");
            });

            modelBuilder.Entity<DosageForm>(entity =>
            {
                entity.HasKey(e => e.DosageId);

                entity.Property(e => e.DosageId)
                    .ValueGeneratedNever()
                    .HasColumnName("DosageID");

                entity.Property(e => e.DosageDescription).HasMaxLength(50);
            });

            modelBuilder.Entity<HighestQualification>(entity =>
            {
                entity.HasKey(e => e.QualificationId);

                entity.Property(e => e.QualificationId)
                    .ValueGeneratedNever()
                    .HasColumnName("QualificationID");

                entity.Property(e => e.QualificationName).HasMaxLength(50);
            });

            modelBuilder.Entity<InteractionLevel>(entity =>
            {
                entity.Property(e => e.InteractionLevelId)
                    .ValueGeneratedNever()
                    .HasColumnName("InteractionLevelID");

                entity.Property(e => e.InteractionLevelDecsription).HasMaxLength(50);
            });

            modelBuilder.Entity<MedInteractionActiveIngredient>(entity =>
            {
                entity.ToTable("MedInteraction_ActiveIngredient");

                entity.Property(e => e.MedInteractionActiveIngredientId)
                    .ValueGeneratedNever()
                    .HasColumnName("MedInteraction_ActiveIngredientID");

                entity.Property(e => e.IngredientId).HasColumnName("IngredientID");

                entity.Property(e => e.InteractionLevelId).HasColumnName("InteractionLevelID");

                entity.Property(e => e.MedInteractionId).HasColumnName("MedInteractionID");

                entity.HasOne(d => d.Ingredient)
                    .WithMany(p => p.MedInteractionActiveIngredient)
                    .HasForeignKey(d => d.IngredientId)
                    .HasConstraintName("FK_MedInteraction_ActiveIngredient_ActiveIngredient1");

                entity.HasOne(d => d.InteractionLevel)
                    .WithMany(p => p.MedInteractionActiveIngredient)
                    .HasForeignKey(d => d.InteractionLevelId)
                    .HasConstraintName("FK_MedInteraction_ActiveIngredient_InteractionLevel1");

                entity.HasOne(d => d.MedInteraction)
                    .WithMany(p => p.MedInteractionActiveIngredient)
                    .HasForeignKey(d => d.MedInteractionId)
                    .HasConstraintName("FK_MedInteraction_ActiveIngredient_MedicationInteraction");
            });

            modelBuilder.Entity<MedicalPractice>(entity =>
            {
                entity.Property(e => e.MedicalPracticeId)
                    .ValueGeneratedNever()
                    .HasColumnName("MedicalPracticeID");

                entity.Property(e => e.AddressLine1).HasMaxLength(50);

                entity.Property(e => e.AddressLine2).HasMaxLength(50);

                entity.Property(e => e.CityId).HasColumnName("CityID");

                entity.Property(e => e.PracticeContactNo)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.PracticeEmail).HasMaxLength(50);

                entity.Property(e => e.PracticeName).HasMaxLength(50);

                entity.Property(e => e.PracticeNo)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.HasOne(d => d.City)
                    .WithMany(p => p.MedicalPractice)
                    .HasForeignKey(d => d.CityId)
                    .HasConstraintName("FK_MedicalPractice_City");
            });

            modelBuilder.Entity<MedicationInteraction>(entity =>
            {
                entity.HasKey(e => e.MedInteractionId);

                entity.Property(e => e.MedInteractionId)
                    .ValueGeneratedNever()
                    .HasColumnName("MedInteractionID");

                entity.Property(e => e.ActiveIngredient1).HasMaxLength(50);

                entity.Property(e => e.ActiveIngredient2).HasMaxLength(50);

                entity.Property(e => e.IngredientId).HasColumnName("IngredientID");

                entity.HasOne(d => d.Ingredient)
                    .WithMany(p => p.MedicationInteraction)
                    .HasForeignKey(d => d.IngredientId)
                    .HasConstraintName("FK_MedicationInteraction_ActiveIngredient");
            });

            modelBuilder.Entity<MedicationRecord>(entity =>
            {
                entity.HasKey(e => e.MedicationId);

                entity.Property(e => e.MedicationId)
                    .ValueGeneratedNever()
                    .HasColumnName("MedicationID");

                entity.Property(e => e.IngredientId).HasColumnName("IngredientID");

                entity.Property(e => e.MedicationName).HasMaxLength(50);

                entity.Property(e => e.ScheduleId).HasColumnName("ScheduleID");

                entity.HasOne(d => d.Ingredient)
                    .WithMany(p => p.MedicationRecord)
                    .HasForeignKey(d => d.IngredientId)
                    .HasConstraintName("FK_MedicationRecord_ActiveIngredient");

                entity.HasOne(d => d.Schedule)
                    .WithMany(p => p.MedicationRecord)
                    .HasForeignKey(d => d.ScheduleId)
                    .HasConstraintName("FK_MedicationRecord_Schedule");
            });

            modelBuilder.Entity<Patient>(entity =>
            {
                entity.Property(e => e.PatientId)
                    .ValueGeneratedNever()
                    .HasColumnName("PatientID");

                entity.Property(e => e.Dob)
                    .HasMaxLength(20)
                    .HasColumnName("DOB");

                entity.Property(e => e.Idnumber)
                    .HasMaxLength(13)
                    .HasColumnName("IDNumber")
                    .IsFixedLength(true);
            });

            modelBuilder.Entity<PatientAllergy>(entity =>
            {
                entity.HasKey(e => e.AllergyId);

                entity.Property(e => e.AllergyId)
                    .ValueGeneratedNever()
                    .HasColumnName("AllergyID");

                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.Property(e => e.DoctorId).HasColumnName("DoctorID");

                entity.Property(e => e.IngredientId).HasColumnName("IngredientID");

                entity.Property(e => e.PatientId).HasColumnName("PatientID");

                entity.HasOne(d => d.Doctor)
                    .WithMany(p => p.PatientAllergy)
                    .HasForeignKey(d => d.DoctorId)
                    .HasConstraintName("FK_PatientAllergy_Doctor");

                entity.HasOne(d => d.Ingredient)
                    .WithMany(p => p.PatientAllergy)
                    .HasForeignKey(d => d.IngredientId)
                    .HasConstraintName("FK_PatientAllergy_ActiveIngredient");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.PatientAllergy)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK_PatientAllergy_Patient");
            });

            modelBuilder.Entity<PatientDoctorVisit>(entity =>
            {
                entity.Property(e => e.PatientDoctorVisitId)
                    .ValueGeneratedNever()
                    .HasColumnName("PatientDoctorVisitID");

                entity.Property(e => e.DoctorId).HasColumnName("DoctorID");

                entity.Property(e => e.PatientId).HasColumnName("PatientID");

                entity.Property(e => e.VisitDate).HasColumnType("datetime");

                entity.HasOne(d => d.Doctor)
                    .WithMany(p => p.PatientDoctorVisit)
                    .HasForeignKey(d => d.DoctorId)
                    .HasConstraintName("FK_PatientDoctorVisit_Doctor");

                entity.HasOne(d => d.Patient)
                    .WithMany(p => p.PatientDoctorVisit)
                    .HasForeignKey(d => d.PatientId)
                    .HasConstraintName("FK_PatientDoctorVisit_Patient");
            });

            modelBuilder.Entity<Pharmacist>(entity =>
            {
                entity.Property(e => e.PharmacistId)
                    .ValueGeneratedNever()
                    .HasColumnName("PharmacistID");

                entity.Property(e => e.PharmacyId).HasColumnName("PharmacyID");

                entity.Property(e => e.RegNumber)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.HasOne(d => d.Pharmacy)
                    .WithMany(p => p.Pharmacist)
                    .HasForeignKey(d => d.PharmacyId)
                    .HasConstraintName("FK_Pharmacist_Pharmacy");
            });

            modelBuilder.Entity<Pharmacy>(entity =>
            {
                entity.Property(e => e.PharmacyId)
                    .ValueGeneratedNever()
                    .HasColumnName("PharmacyID");

                entity.Property(e => e.AddressLine1).HasMaxLength(50);

                entity.Property(e => e.AddressLine2).HasMaxLength(50);

                entity.Property(e => e.CityId).HasColumnName("CityID");

                entity.Property(e => e.LicenseNo)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.PharmacyContactNo)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.PharmacyEmail).HasMaxLength(50);

                entity.Property(e => e.PharmacyName).HasMaxLength(50);

                entity.HasOne(d => d.City)
                    .WithMany(p => p.Pharmacy)
                    .HasForeignKey(d => d.CityId)
                    .HasConstraintName("FK_Pharmacy_City");
            });

            modelBuilder.Entity<Prescription>(entity =>
            {
                entity.Property(e => e.PrescriptionId)
                    .ValueGeneratedNever()
                    .HasColumnName("PrescriptionID");

                entity.Property(e => e.ConditionId).HasColumnName("ConditionID");

                entity.Property(e => e.DosageId).HasColumnName("DosageID");

                entity.Property(e => e.Instruction).HasMaxLength(50);

                entity.Property(e => e.MedicationId).HasColumnName("MedicationID");

                entity.HasOne(d => d.Condition)
                    .WithMany(p => p.Prescription)
                    .HasForeignKey(d => d.ConditionId)
                    .HasConstraintName("FK_Prescription_ConditionDiagnosis");

                entity.HasOne(d => d.Dosage)
                    .WithMany(p => p.Prescription)
                    .HasForeignKey(d => d.DosageId)
                    .HasConstraintName("FK_Prescription_DosageForm");

                entity.HasOne(d => d.Medication)
                    .WithMany(p => p.Prescription)
                    .HasForeignKey(d => d.MedicationId)
                    .HasConstraintName("FK_Prescription_MedicationRecord");
            });

            modelBuilder.Entity<PrescriptionMedication>(entity =>
            {
                entity.ToTable("Prescription_Medication");

                entity.Property(e => e.PrescriptionMedicationId)
                    .ValueGeneratedNever()
                    .HasColumnName("PrescriptionMedicationID");

                entity.Property(e => e.ContraIndicationId).HasColumnName("ContraIndicationID");

                entity.Property(e => e.DosageId).HasColumnName("DosageID");

                entity.Property(e => e.Instruction).HasMaxLength(50);

                entity.Property(e => e.MedInteractionId).HasColumnName("MedInteractionID");

                entity.Property(e => e.MedicationId).HasColumnName("MedicationID");

                entity.Property(e => e.PatientDoctorVisitId).HasColumnName("PatientDoctorVisitID");

                entity.Property(e => e.PrescriptionDate).HasColumnType("datetime");

                entity.Property(e => e.PrescriptionId).HasColumnName("PrescriptionID");

                entity.Property(e => e.Quantity).HasMaxLength(50);

                entity.Property(e => e.RepeatId).HasColumnName("RepeatID");

                entity.Property(e => e.Status).HasMaxLength(50);

                entity.Property(e => e.WarningIgnoreReason).HasMaxLength(50);

                entity.HasOne(d => d.ContraIndication)
                    .WithMany(p => p.PrescriptionMedication)
                    .HasForeignKey(d => d.ContraIndicationId)
                    .HasConstraintName("FK_Prescription_Medication_ContraIndication");

                entity.HasOne(d => d.Dosage)
                    .WithMany(p => p.PrescriptionMedication)
                    .HasForeignKey(d => d.DosageId)
                    .HasConstraintName("FK_Prescription_Medication_DosageForm");

                entity.HasOne(d => d.MedInteraction)
                    .WithMany(p => p.PrescriptionMedication)
                    .HasForeignKey(d => d.MedInteractionId)
                    .HasConstraintName("FK_Prescription_Medication_MedicationInteraction");

                entity.HasOne(d => d.Medication)
                    .WithMany(p => p.PrescriptionMedication)
                    .HasForeignKey(d => d.MedicationId)
                    .HasConstraintName("FK_Prescription_Medication_MedicationRecord");

                entity.HasOne(d => d.PatientDoctorVisit)
                    .WithMany(p => p.PrescriptionMedication)
                    .HasForeignKey(d => d.PatientDoctorVisitId)
                    .HasConstraintName("FK_Prescription_Medication_PatientDoctorVisit");

                entity.HasOne(d => d.Repeat)
                    .WithMany(p => p.PrescriptionMedication)
                    .HasForeignKey(d => d.RepeatId)
                    .HasConstraintName("FK_Prescription_Medication_Repeat");
            });

            modelBuilder.Entity<Repeat>(entity =>
            {
                entity.Property(e => e.RepeatId)
                    .ValueGeneratedNever()
                    .HasColumnName("RepeatID");

                entity.Property(e => e.RepeatDescription).HasMaxLength(50);
            });

            modelBuilder.Entity<Schedule>(entity =>
            {
                entity.Property(e => e.ScheduleId)
                    .ValueGeneratedNever()
                    .HasColumnName("ScheduleID");

                entity.Property(e => e.ScheduleDescription).HasMaxLength(50);
            });

            modelBuilder.Entity<Suburb>(entity =>
            {
                entity.Property(e => e.SuburbId)
                    .ValueGeneratedNever()
                    .HasColumnName("SuburbID");

                entity.Property(e => e.CityId).HasColumnName("CityID");

                entity.Property(e => e.SuburbName).HasMaxLength(50);

                entity.HasOne(d => d.City)
                    .WithMany(p => p.Suburb)
                    .HasForeignKey(d => d.CityId)
                    .HasConstraintName("FK_Suburb_City");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.UserId)
                    .ValueGeneratedNever()
                    .HasColumnName("UserID");

                entity.Property(e => e.AddressLine1).HasMaxLength(50);

                entity.Property(e => e.AddressLine2).HasMaxLength(50);

                entity.Property(e => e.CityId).HasColumnName("CityID");

                entity.Property(e => e.ContactNo)
                    .HasMaxLength(10)
                    .IsFixedLength(true);

                entity.Property(e => e.Email).HasMaxLength(50);

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Password).HasMaxLength(50);

                entity.Property(e => e.Surname).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);

                entity.Property(e => e.UserType).HasMaxLength(50);

                entity.HasOne(d => d.City)
                    .WithMany(p => p.User)
                    .HasForeignKey(d => d.CityId)
                    .HasConstraintName("FK_User_City");

                entity.HasOne(d => d.UserNavigation)
                    .WithOne(p => p.User)
                    .HasForeignKey<User>(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_User_Admin");

                entity.HasOne(d => d.User1)
                    .WithOne(p => p.User)
                    .HasForeignKey<User>(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_User_Doctor");

                entity.HasOne(d => d.User2)
                    .WithOne(p => p.User)
                    .HasForeignKey<User>(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_User_Pharmacist");

                entity.HasOne(d => d.User3)
                    .WithOne(p => p.User)
                    .HasForeignKey<User>(d => d.UserId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_User_Pharmacy");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}