// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class HighestQualification
    {
        public HighestQualification()
        {
            Doctor = new HashSet<Doctor>();
        }

        public int QualificationId { get; set; }
        public string QualificationName { get; set; }

        public virtual ICollection<Doctor> Doctor { get; set; }
    }
}