// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class MedicationRecord
    {
        public MedicationRecord()
        {
            ChronicMedication = new HashSet<ChronicMedication>();
            DispensedMedication = new HashSet<DispensedMedication>();
            Prescription = new HashSet<Prescription>();
            PrescriptionMedication = new HashSet<PrescriptionMedication>();
        }

        public int MedicationId { get; set; }
        public string MedicationName { get; set; }
        public int? IngredientId { get; set; }
        public int? ScheduleId { get; set; }

        public virtual ActiveIngredient Ingredient { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ICollection<ChronicMedication> ChronicMedication { get; set; }
        public virtual ICollection<DispensedMedication> DispensedMedication { get; set; }
        public virtual ICollection<Prescription> Prescription { get; set; }
        public virtual ICollection<PrescriptionMedication> PrescriptionMedication { get; set; }
    }
}