// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class PatientDoctorVisit
    {
        public PatientDoctorVisit()
        {
            PrescriptionMedication = new HashSet<PrescriptionMedication>();
        }

        public int PatientDoctorVisitId { get; set; }
        public DateTime? VisitDate { get; set; }
        public int? PatientId { get; set; }
        public int? DoctorId { get; set; }

        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<PrescriptionMedication> PrescriptionMedication { get; set; }
    }
}