// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class Pharmacist
    {
        public Pharmacist()
        {
            DispensedMedication = new HashSet<DispensedMedication>();
        }

        public int PharmacistId { get; set; }
        public string RegNumber { get; set; }
        public int? PharmacyId { get; set; }

        public virtual Pharmacy Pharmacy { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<DispensedMedication> DispensedMedication { get; set; }
    }
}