// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class Prescription
    {
        public int PrescriptionId { get; set; }
        public int? ConditionId { get; set; }
        public int? MedicationId { get; set; }
        public int? DosageId { get; set; }
        public string Instruction { get; set; }

        public virtual ConditionDiagnosis Condition { get; set; }
        public virtual DosageForm Dosage { get; set; }
        public virtual MedicationRecord Medication { get; set; }
    }
}