// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string UserType { get; set; }
        public int? CityId { get; set; }

        public virtual City City { get; set; }
        public virtual Doctor User1 { get; set; }
        public virtual Pharmacist User2 { get; set; }
        public virtual Pharmacy User3 { get; set; }
        public virtual Admin UserNavigation { get; set; }
    }
}