// <auto-generated />
using System;
using E_prescription.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_prescription.Migrations
{
    [DbContext(typeof(GRP42EPrescriptionContext))]
    [Migration("20221018003735_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_prescription.Models.ActiveIngredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IngredientID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IngredientDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StrengthId")
                        .HasColumnType("int")
                        .HasColumnName("StrengthID");

                    b.HasKey("IngredientId");

                    b.HasIndex("StrengthId");

                    b.ToTable("ActiveIngredient");
                });

            modelBuilder.Entity("E_prescription.Models.ActiveIngredientStrength", b =>
                {
                    b.Property<int>("StrengthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StrengthID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrengthDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StrengthId");

                    b.ToTable("ActiveIngredientStrength");
                });

            modelBuilder.Entity("E_prescription.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("E_prescription.Models.ChronicHistory", b =>
                {
                    b.Property<int>("ChronicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChronicID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConditionId")
                        .HasColumnType("int")
                        .HasColumnName("ConditionID");

                    b.Property<string>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.HasKey("ChronicId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("ChronicHistory");
                });

            modelBuilder.Entity("E_prescription.Models.ChronicMedication", b =>
                {
                    b.Property<int>("ChronicMedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChronicMedicationID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int?>("MedicationId")
                        .HasColumnType("int")
                        .HasColumnName("MedicationID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.HasKey("ChronicMedicationId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId");

                    b.ToTable("ChronicMedication");
                });

            modelBuilder.Entity("E_prescription.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength(true);

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    b.HasKey("CityId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("E_prescription.Models.ConditionDiagnosis", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConditionID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConditionDecription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConditionId");

                    b.ToTable("ConditionDiagnosis");
                });

            modelBuilder.Entity("E_prescription.Models.ContraIndication", b =>
                {
                    b.Property<int>("ContraIndicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ContraIndicationID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConditionId")
                        .HasColumnType("int")
                        .HasColumnName("ConditionID");

                    b.Property<string>("ContraIndicationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.HasKey("ContraIndicationId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("IngredientId");

                    b.ToTable("ContraIndication");
                });

            modelBuilder.Entity("E_prescription.Models.DispensedMedication", b =>
                {
                    b.Property<int>("DispensedMedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DispensedMedicationID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContraIndicationId")
                        .HasColumnType("int")
                        .HasColumnName("ContraIndicationID");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("DosageId")
                        .HasColumnType("int")
                        .HasColumnName("DosageID");

                    b.Property<int?>("MedInteractionId")
                        .HasColumnType("int")
                        .HasColumnName("MedInteractionID");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int")
                        .HasColumnName("MedicationID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<int?>("PharmacistId")
                        .HasColumnType("int")
                        .HasColumnName("PharmacistID");

                    b.Property<string>("Quantity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarningIgnoreReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DispensedMedicationId");

                    b.HasIndex("ContraIndicationId");

                    b.HasIndex("DosageId");

                    b.HasIndex("MedInteractionId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("DispensedMedication");
                });

            modelBuilder.Entity("E_prescription.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<string>("Hcrn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HCRN");

                    b.Property<int?>("MedicalPracticeId")
                        .HasColumnType("int")
                        .HasColumnName("MedicalPracticeID");

                    b.Property<int?>("QualificationId")
                        .HasColumnType("int")
                        .HasColumnName("QualificationID");

                    b.HasKey("DoctorId");

                    b.HasIndex("MedicalPracticeId");

                    b.HasIndex("QualificationId");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("E_prescription.Models.DosageForm", b =>
                {
                    b.Property<int>("DosageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DosageID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DosageDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DosageId");

                    b.ToTable("DosageForm");
                });

            modelBuilder.Entity("E_prescription.Models.HighestQualification", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QualificationID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QualificationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QualificationId");

                    b.ToTable("HighestQualification");
                });

            modelBuilder.Entity("E_prescription.Models.InteractionLevel", b =>
                {
                    b.Property<int>("InteractionLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InteractionLevelID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InteractionLevelDecsription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InteractionLevelId");

                    b.ToTable("InteractionLevel");
                });

            modelBuilder.Entity("E_prescription.Models.MedInteractionActiveIngredient", b =>
                {
                    b.Property<int>("MedInteractionActiveIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedInteraction_ActiveIngredientID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<int?>("InteractionLevelId")
                        .HasColumnType("int")
                        .HasColumnName("InteractionLevelID");

                    b.Property<int?>("MedInteractionId")
                        .HasColumnType("int")
                        .HasColumnName("MedInteractionID");

                    b.HasKey("MedInteractionActiveIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("InteractionLevelId");

                    b.HasIndex("MedInteractionId");

                    b.ToTable("MedInteraction_ActiveIngredient");
                });

            modelBuilder.Entity("E_prescription.Models.MedicalPractice", b =>
                {
                    b.Property<int>("MedicalPracticeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicalPracticeID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<string>("PracticeContactNo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("PracticeEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PracticeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PracticeNo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID");

                    b.Property<int?>("SuburbId")
                        .HasColumnType("int")
                        .HasColumnName("SuburbID");

                    b.HasKey("MedicalPracticeId");

                    b.HasIndex("CityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SuburbId");

                    b.ToTable("MedicalPractice");
                });

            modelBuilder.Entity("E_prescription.Models.MedicationActiveIngredient", b =>
                {
                    b.Property<int>("MedicationIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicationIngredientID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<int?>("MedicationId")
                        .HasColumnType("int")
                        .HasColumnName("MedicationID");

                    b.HasKey("MedicationIngredientId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MedicationId");

                    b.ToTable("Medication_ActiveIngredient");
                });

            modelBuilder.Entity("E_prescription.Models.MedicationInteraction", b =>
                {
                    b.Property<int>("MedInteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedInteractionID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveIngredient1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActiveIngredient2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.HasKey("MedInteractionId");

                    b.HasIndex("IngredientId");

                    b.ToTable("MedicationInteraction");
                });

            modelBuilder.Entity("E_prescription.Models.MedicationRecord", b =>
                {
                    b.Property<int>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicationID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DosageId")
                        .HasColumnType("int")
                        .HasColumnName("DosageID");

                    b.Property<string>("MedicationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    b.HasKey("MedicationId");

                    b.HasIndex("DosageId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("MedicationRecord");
                });

            modelBuilder.Entity("E_prescription.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<string>("Dob")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DOB");

                    b.Property<string>("Idnumber")
                        .HasMaxLength(13)
                        .HasColumnType("nchar(13)")
                        .HasColumnName("IDNumber")
                        .IsFixedLength(true);

                    b.HasKey("PatientId");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("E_prescription.Models.PatientAllergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AllergyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.HasKey("AllergyId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientAllergy");
                });

            modelBuilder.Entity("E_prescription.Models.PatientDoctorVisit", b =>
                {
                    b.Property<int>("PatientDoctorVisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PatientDoctorVisitID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.Property<DateTime?>("VisitDate")
                        .HasColumnType("datetime");

                    b.HasKey("PatientDoctorVisitId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientDoctorVisit");
                });

            modelBuilder.Entity("E_prescription.Models.Pharmacist", b =>
                {
                    b.Property<int>("PharmacistId")
                        .HasColumnType("int")
                        .HasColumnName("PharmacistID");

                    b.Property<int?>("PharmacyId")
                        .HasColumnType("int")
                        .HasColumnName("PharmacyID");

                    b.Property<string>("RegNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.HasKey("PharmacistId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Pharmacist");
                });

            modelBuilder.Entity("E_prescription.Models.Pharmacy", b =>
                {
                    b.Property<int>("PharmacyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PharmacyID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseNo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("PharmacyContactNo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("PharmacyEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PharmacyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SuburbId")
                        .HasColumnType("int")
                        .HasColumnName("SuburbID");

                    b.HasKey("PharmacyId");

                    b.ToTable("Pharmacy");
                });

            modelBuilder.Entity("E_prescription.Models.PostalCode", b =>
                {
                    b.Property<int>("PostalCodeId")
                        .HasColumnType("int")
                        .HasColumnName("PostalCodeID");

                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<string>("PostalCodeName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PostalCodeId");

                    b.HasIndex("CityId");

                    b.ToTable("PostalCode");
                });

            modelBuilder.Entity("E_prescription.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConditionId")
                        .HasColumnType("int")
                        .HasColumnName("ConditionID");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("PatientID");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("ConditionId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("E_prescription.Models.PrescriptionMedication", b =>
                {
                    b.Property<int>("PrescriptionMedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionMedicationID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AllergyId")
                        .HasColumnType("int")
                        .HasColumnName("AllergyID");

                    b.Property<string>("AllergyIgnoreReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContraIgnoreReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContraIndicationId")
                        .HasColumnType("int")
                        .HasColumnName("ContraIndicationID");

                    b.Property<string>("DispensedStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedInteractionId")
                        .HasColumnType("int")
                        .HasColumnName("MedInteractionID");

                    b.Property<int?>("MedicationId")
                        .HasColumnType("int")
                        .HasColumnName("MedicationID");

                    b.Property<int?>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    b.Property<string>("Quantity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RepeatId")
                        .HasColumnType("int")
                        .HasColumnName("RepeatID");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarningIgnoreReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionMedicationId");

                    b.HasIndex("AllergyId");

                    b.HasIndex("ContraIndicationId");

                    b.HasIndex("MedInteractionId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("RepeatId");

                    b.ToTable("Prescription_Medication");
                });

            modelBuilder.Entity("E_prescription.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProvinceID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProvinceName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("E_prescription.Models.Repeat", b =>
                {
                    b.Property<int>("RepeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RepeatID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RepeatDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RepeatId");

                    b.ToTable("Repeat");
                });

            modelBuilder.Entity("E_prescription.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ScheduleDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("E_prescription.Models.Suburb", b =>
                {
                    b.Property<int>("SuburbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SuburbID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<string>("SuburbName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SuburbId");

                    b.HasIndex("CityId");

                    b.ToTable("Suburb");
                });

            modelBuilder.Entity("E_prescription.Models.TblUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SuburbId")
                        .HasColumnType("int")
                        .HasColumnName("SuburbID");

                    b.Property<string>("Surname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK_User");

                    b.HasIndex("SuburbId");

                    b.ToTable("tblUser");
                });

            modelBuilder.Entity("E_prescription.Models.ActiveIngredient", b =>
                {
                    b.HasOne("E_prescription.Models.ActiveIngredientStrength", "Strength")
                        .WithMany("ActiveIngredients")
                        .HasForeignKey("StrengthId")
                        .HasConstraintName("FK_ActiveIngredient_ActiveIngredientStrength");

                    b.Navigation("Strength");
                });

            modelBuilder.Entity("E_prescription.Models.Admin", b =>
                {
                    b.HasOne("E_prescription.Models.TblUser", "AdminNavigation")
                        .WithOne("Admin")
                        .HasForeignKey("E_prescription.Models.Admin", "AdminId")
                        .HasConstraintName("FK_Admin_tblUser")
                        .IsRequired();

                    b.Navigation("AdminNavigation");
                });

            modelBuilder.Entity("E_prescription.Models.ChronicHistory", b =>
                {
                    b.HasOne("E_prescription.Models.ConditionDiagnosis", "Condition")
                        .WithMany("ChronicHistories")
                        .HasForeignKey("ConditionId")
                        .HasConstraintName("FK_ChronicHistory_ConditionDiagnosis");

                    b.HasOne("E_prescription.Models.Doctor", "Doctor")
                        .WithMany("ChronicHistories")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK_ChronicHistory_Doctor");

                    b.HasOne("E_prescription.Models.Patient", "Patient")
                        .WithMany("ChronicHistories")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_ChronicHistory_Patient");

                    b.Navigation("Condition");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("E_prescription.Models.ChronicMedication", b =>
                {
                    b.HasOne("E_prescription.Models.Doctor", "Doctor")
                        .WithMany("ChronicMedications")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK_ChronicMedication_Doctor");

                    b.HasOne("E_prescription.Models.MedicationRecord", "Medication")
                        .WithMany("ChronicMedications")
                        .HasForeignKey("MedicationId")
                        .HasConstraintName("FK_ChronicMedication_MedicationRecord");

                    b.HasOne("E_prescription.Models.Patient", "Patient")
                        .WithMany("ChronicMedications")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_ChronicMedication_Patient");

                    b.Navigation("Doctor");

                    b.Navigation("Medication");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("E_prescription.Models.City", b =>
                {
                    b.HasOne("E_prescription.Models.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .HasConstraintName("FK_City_Province");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("E_prescription.Models.ContraIndication", b =>
                {
                    b.HasOne("E_prescription.Models.ConditionDiagnosis", "Condition")
                        .WithMany("ContraIndications")
                        .HasForeignKey("ConditionId")
                        .HasConstraintName("FK_ContraIndication_ConditionDiagnosis");

                    b.HasOne("E_prescription.Models.ActiveIngredient", "Ingredient")
                        .WithMany("ContraIndications")
                        .HasForeignKey("IngredientId")
                        .HasConstraintName("FK_ContraIndication_ActiveIngredient");

                    b.Navigation("Condition");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("E_prescription.Models.DispensedMedication", b =>
                {
                    b.HasOne("E_prescription.Models.ContraIndication", "ContraIndication")
                        .WithMany("DispensedMedications")
                        .HasForeignKey("ContraIndicationId")
                        .HasConstraintName("FK_DispensedMedication_ContraIndication");

                    b.HasOne("E_prescription.Models.DosageForm", "Dosage")
                        .WithMany("DispensedMedications")
                        .HasForeignKey("DosageId")
                        .HasConstraintName("FK_DispensedMedication_DosageForm");

                    b.HasOne("E_prescription.Models.MedicationInteraction", "MedInteraction")
                        .WithMany("DispensedMedications")
                        .HasForeignKey("MedInteractionId")
                        .HasConstraintName("FK_DispensedMedication_MedicationInteraction");

                    b.HasOne("E_prescription.Models.MedicationRecord", "Medication")
                        .WithMany("DispensedMedications")
                        .HasForeignKey("MedicationId")
                        .HasConstraintName("FK_DispensedMedication_MedicationRecord")
                        .IsRequired();

                    b.HasOne("E_prescription.Models.Patient", "Patient")
                        .WithMany("DispensedMedications")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_DispensedMedication_Patient");

                    b.HasOne("E_prescription.Models.Pharmacist", "Pharmacist")
                        .WithMany("DispensedMedications")
                        .HasForeignKey("PharmacistId")
                        .HasConstraintName("FK_DispensedMedication_Pharmacist");

                    b.Navigation("ContraIndication");

                    b.Navigation("Dosage");

                    b.Navigation("Medication");

                    b.Navigation("MedInteraction");

                    b.Navigation("Patient");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("E_prescription.Models.Doctor", b =>
                {
                    b.HasOne("E_prescription.Models.TblUser", "DoctorNavigation")
                        .WithOne("Doctor")
                        .HasForeignKey("E_prescription.Models.Doctor", "DoctorId")
                        .HasConstraintName("FK_Doctor_tblUser")
                        .IsRequired();

                    b.HasOne("E_prescription.Models.MedicalPractice", "MedicalPractice")
                        .WithMany("Doctors")
                        .HasForeignKey("MedicalPracticeId")
                        .HasConstraintName("FK_Doctor_MedicalPractice");

                    b.HasOne("E_prescription.Models.HighestQualification", "Qualification")
                        .WithMany("Doctors")
                        .HasForeignKey("QualificationId")
                        .HasConstraintName("FK_Doctor_HighestQualification");

                    b.Navigation("DoctorNavigation");

                    b.Navigation("MedicalPractice");

                    b.Navigation("Qualification");
                });

            modelBuilder.Entity("E_prescription.Models.MedInteractionActiveIngredient", b =>
                {
                    b.HasOne("E_prescription.Models.ActiveIngredient", "Ingredient")
                        .WithMany("MedInteractionActiveIngredients")
                        .HasForeignKey("IngredientId")
                        .HasConstraintName("FK_MedInteraction_ActiveIngredient_ActiveIngredient1");

                    b.HasOne("E_prescription.Models.InteractionLevel", "InteractionLevel")
                        .WithMany("MedInteractionActiveIngredients")
                        .HasForeignKey("InteractionLevelId")
                        .HasConstraintName("FK_MedInteraction_ActiveIngredient_InteractionLevel1");

                    b.HasOne("E_prescription.Models.MedicationInteraction", "MedInteraction")
                        .WithMany("MedInteractionActiveIngredients")
                        .HasForeignKey("MedInteractionId")
                        .HasConstraintName("FK_MedInteraction_ActiveIngredient_MedicationInteraction");

                    b.Navigation("Ingredient");

                    b.Navigation("InteractionLevel");

                    b.Navigation("MedInteraction");
                });

            modelBuilder.Entity("E_prescription.Models.MedicalPractice", b =>
                {
                    b.HasOne("E_prescription.Models.City", "City")
                        .WithMany("MedicalPractices")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_MedicalPractice_City");

                    b.HasOne("E_prescription.Models.Province", "Province")
                        .WithMany("MedicalPractices")
                        .HasForeignKey("ProvinceId")
                        .HasConstraintName("FK_MedicalPractice_Province");

                    b.HasOne("E_prescription.Models.Suburb", "Suburb")
                        .WithMany("MedicalPractices")
                        .HasForeignKey("SuburbId")
                        .HasConstraintName("FK_MedicalPractice_Suburb");

                    b.Navigation("City");

                    b.Navigation("Province");

                    b.Navigation("Suburb");
                });

            modelBuilder.Entity("E_prescription.Models.MedicationActiveIngredient", b =>
                {
                    b.HasOne("E_prescription.Models.ActiveIngredient", "Ingredient")
                        .WithMany("MedicationActiveIngredients")
                        .HasForeignKey("IngredientId")
                        .HasConstraintName("FK_Medication_ActiveIngredient_ActiveIngredient");

                    b.HasOne("E_prescription.Models.MedicationRecord", "Medication")
                        .WithMany("MedicationActiveIngredients")
                        .HasForeignKey("MedicationId")
                        .HasConstraintName("FK_Medication_ActiveIngredient_MedicationRecord");

                    b.Navigation("Ingredient");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("E_prescription.Models.MedicationInteraction", b =>
                {
                    b.HasOne("E_prescription.Models.ActiveIngredient", "Ingredient")
                        .WithMany("MedicationInteractions")
                        .HasForeignKey("IngredientId")
                        .HasConstraintName("FK_MedicationInteraction_ActiveIngredient");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("E_prescription.Models.MedicationRecord", b =>
                {
                    b.HasOne("E_prescription.Models.DosageForm", "Dosage")
                        .WithMany("MedicationRecords")
                        .HasForeignKey("DosageId")
                        .HasConstraintName("FK_MedicationRecord_DosageForm");

                    b.HasOne("E_prescription.Models.Schedule", "Schedule")
                        .WithMany("MedicationRecords")
                        .HasForeignKey("ScheduleId")
                        .HasConstraintName("FK_MedicationRecord_Schedule");

                    b.Navigation("Dosage");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("E_prescription.Models.Patient", b =>
                {
                    b.HasOne("E_prescription.Models.TblUser", "PatientNavigation")
                        .WithOne("Patient")
                        .HasForeignKey("E_prescription.Models.Patient", "PatientId")
                        .HasConstraintName("FK_Patient_tblUser")
                        .IsRequired();

                    b.Navigation("PatientNavigation");
                });

            modelBuilder.Entity("E_prescription.Models.PatientAllergy", b =>
                {
                    b.HasOne("E_prescription.Models.Doctor", "Doctor")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK_PatientAllergy_Doctor");

                    b.HasOne("E_prescription.Models.ActiveIngredient", "Ingredient")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("IngredientId")
                        .HasConstraintName("FK_PatientAllergy_ActiveIngredient");

                    b.HasOne("E_prescription.Models.Patient", "Patient")
                        .WithMany("PatientAllergies")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_PatientAllergy_Patient");

                    b.Navigation("Doctor");

                    b.Navigation("Ingredient");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("E_prescription.Models.PatientDoctorVisit", b =>
                {
                    b.HasOne("E_prescription.Models.Doctor", "Doctor")
                        .WithMany("PatientDoctorVisits")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK_PatientDoctorVisit_Doctor");

                    b.HasOne("E_prescription.Models.Patient", "Patient")
                        .WithMany("PatientDoctorVisits")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_PatientDoctorVisit_Patient");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("E_prescription.Models.Pharmacist", b =>
                {
                    b.HasOne("E_prescription.Models.TblUser", "PharmacistNavigation")
                        .WithOne("Pharmacist")
                        .HasForeignKey("E_prescription.Models.Pharmacist", "PharmacistId")
                        .HasConstraintName("FK_Pharmacist_tblUser")
                        .IsRequired();

                    b.HasOne("E_prescription.Models.Pharmacy", "Pharmacy")
                        .WithMany("Pharmacists")
                        .HasForeignKey("PharmacyId")
                        .HasConstraintName("FK_Pharmacist_Pharmacy");

                    b.Navigation("PharmacistNavigation");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("E_prescription.Models.PostalCode", b =>
                {
                    b.HasOne("E_prescription.Models.City", "City")
                        .WithMany("PostalCodes")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_PostalCode_PostalCode")
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("E_prescription.Models.Prescription", b =>
                {
                    b.HasOne("E_prescription.Models.ConditionDiagnosis", "Condition")
                        .WithMany("Prescriptions")
                        .HasForeignKey("ConditionId")
                        .HasConstraintName("FK_Prescription_ConditionDiagnosis");

                    b.HasOne("E_prescription.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK_Prescription_Doctor");

                    b.HasOne("E_prescription.Models.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK_Prescription_Patient");

                    b.Navigation("Condition");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("E_prescription.Models.PrescriptionMedication", b =>
                {
                    b.HasOne("E_prescription.Models.PatientAllergy", "Allergy")
                        .WithMany("PrescriptionMedications")
                        .HasForeignKey("AllergyId")
                        .HasConstraintName("FK_Prescription_Medication_PatientAllergy");

                    b.HasOne("E_prescription.Models.ContraIndication", "ContraIndication")
                        .WithMany("PrescriptionMedications")
                        .HasForeignKey("ContraIndicationId")
                        .HasConstraintName("FK_Prescription_Medication_ContraIndication");

                    b.HasOne("E_prescription.Models.MedicationInteraction", "MedInteraction")
                        .WithMany("PrescriptionMedications")
                        .HasForeignKey("MedInteractionId")
                        .HasConstraintName("FK_Prescription_Medication_MedicationInteraction");

                    b.HasOne("E_prescription.Models.MedicationRecord", "Medication")
                        .WithMany("PrescriptionMedications")
                        .HasForeignKey("MedicationId")
                        .HasConstraintName("FK_Prescription_Medication_MedicationRecord");

                    b.HasOne("E_prescription.Models.Repeat", "Repeat")
                        .WithMany("PrescriptionMedications")
                        .HasForeignKey("RepeatId")
                        .HasConstraintName("FK_Prescription_Medication_Repeat");

                    b.Navigation("Allergy");

                    b.Navigation("ContraIndication");

                    b.Navigation("Medication");

                    b.Navigation("MedInteraction");

                    b.Navigation("Repeat");
                });

            modelBuilder.Entity("E_prescription.Models.Suburb", b =>
                {
                    b.HasOne("E_prescription.Models.City", "City")
                        .WithMany("Suburbs")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Suburb_City");

                    b.Navigation("City");
                });

            modelBuilder.Entity("E_prescription.Models.TblUser", b =>
                {
                    b.HasOne("E_prescription.Models.Suburb", "Suburb")
                        .WithMany("TblUsers")
                        .HasForeignKey("SuburbId")
                        .HasConstraintName("FK_User_Suburb");

                    b.Navigation("Suburb");
                });

            modelBuilder.Entity("E_prescription.Models.ActiveIngredient", b =>
                {
                    b.Navigation("ContraIndications");

                    b.Navigation("MedicationActiveIngredients");

                    b.Navigation("MedicationInteractions");

                    b.Navigation("MedInteractionActiveIngredients");

                    b.Navigation("PatientAllergies");
                });

            modelBuilder.Entity("E_prescription.Models.ActiveIngredientStrength", b =>
                {
                    b.Navigation("ActiveIngredients");
                });

            modelBuilder.Entity("E_prescription.Models.City", b =>
                {
                    b.Navigation("MedicalPractices");

                    b.Navigation("PostalCodes");

                    b.Navigation("Suburbs");
                });

            modelBuilder.Entity("E_prescription.Models.ConditionDiagnosis", b =>
                {
                    b.Navigation("ChronicHistories");

                    b.Navigation("ContraIndications");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("E_prescription.Models.ContraIndication", b =>
                {
                    b.Navigation("DispensedMedications");

                    b.Navigation("PrescriptionMedications");
                });

            modelBuilder.Entity("E_prescription.Models.Doctor", b =>
                {
                    b.Navigation("ChronicHistories");

                    b.Navigation("ChronicMedications");

                    b.Navigation("PatientAllergies");

                    b.Navigation("PatientDoctorVisits");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("E_prescription.Models.DosageForm", b =>
                {
                    b.Navigation("DispensedMedications");

                    b.Navigation("MedicationRecords");
                });

            modelBuilder.Entity("E_prescription.Models.HighestQualification", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("E_prescription.Models.InteractionLevel", b =>
                {
                    b.Navigation("MedInteractionActiveIngredients");
                });

            modelBuilder.Entity("E_prescription.Models.MedicalPractice", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("E_prescription.Models.MedicationInteraction", b =>
                {
                    b.Navigation("DispensedMedications");

                    b.Navigation("MedInteractionActiveIngredients");

                    b.Navigation("PrescriptionMedications");
                });

            modelBuilder.Entity("E_prescription.Models.MedicationRecord", b =>
                {
                    b.Navigation("ChronicMedications");

                    b.Navigation("DispensedMedications");

                    b.Navigation("MedicationActiveIngredients");

                    b.Navigation("PrescriptionMedications");
                });

            modelBuilder.Entity("E_prescription.Models.Patient", b =>
                {
                    b.Navigation("ChronicHistories");

                    b.Navigation("ChronicMedications");

                    b.Navigation("DispensedMedications");

                    b.Navigation("PatientAllergies");

                    b.Navigation("PatientDoctorVisits");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("E_prescription.Models.PatientAllergy", b =>
                {
                    b.Navigation("PrescriptionMedications");
                });

            modelBuilder.Entity("E_prescription.Models.Pharmacist", b =>
                {
                    b.Navigation("DispensedMedications");
                });

            modelBuilder.Entity("E_prescription.Models.Pharmacy", b =>
                {
                    b.Navigation("Pharmacists");
                });

            modelBuilder.Entity("E_prescription.Models.Province", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("MedicalPractices");
                });

            modelBuilder.Entity("E_prescription.Models.Repeat", b =>
                {
                    b.Navigation("PrescriptionMedications");
                });

            modelBuilder.Entity("E_prescription.Models.Schedule", b =>
                {
                    b.Navigation("MedicationRecords");
                });

            modelBuilder.Entity("E_prescription.Models.Suburb", b =>
                {
                    b.Navigation("MedicalPractices");

                    b.Navigation("TblUsers");
                });

            modelBuilder.Entity("E_prescription.Models.TblUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Pharmacist");
                });
#pragma warning restore 612, 618
        }
    }
}
