// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class InteractionLevel
    {
        public InteractionLevel()
        {
            MedInteractionActiveIngredient = new HashSet<MedInteractionActiveIngredient>();
        }

        public int InteractionLevelId { get; set; }
        public string InteractionLevelDecsription { get; set; }

        public virtual ICollection<MedInteractionActiveIngredient> MedInteractionActiveIngredient { get; set; }
    }
}