// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace E_prescription
{
    public partial class MedInteractionActiveIngredient
    {
        public int MedInteractionActiveIngredientId { get; set; }
        public int? MedInteractionId { get; set; }
        public int? IngredientId { get; set; }
        public int? InteractionLevelId { get; set; }

        public virtual ActiveIngredient Ingredient { get; set; }
        public virtual InteractionLevel InteractionLevel { get; set; }
        public virtual MedicationInteraction MedInteraction { get; set; }
    }
}